name: Deploy to demo-blur (azure storage)

on:
  push:
    branches:
      - demo-blur

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 4.x
        uses: actions/setup-node@v1
        with:
          node-version: '4.x'
      - uses: actions/checkout@v2
        with:
          ref: demo-blur
      - name: npm install, gulp, build
        run: |
          npm install
          gulp build

      # Azure CLI Upload to storage
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch -d '$web' -s release --account-name bluradmin --debug

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
